version: '3'
services:
  web:
    image: "nginx:1-alpine"
    ports:
      - "8001:80"
    depends_on:
      - "php"
    volumes:
      - "./docker/default.conf:/etc/nginx/conf.d/default.conf"
      - "./html:/var/www/html"
  php:
    image: "php:7.2-fpm-alpine"
    depends_on:
      - "mysql"
    volumes:
      - "./:/var/www"
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
volumes:
  db-data: